// Generated by CoffeeScript 1.9.3
var Card, Ranks, Suits;

Card = (function() {
  function Card(suit, rank) {
    this.suit = suit;
    this.rank = rank;
    this.visible = false;
  }

  return Card;

})();

Suits = ['Heart', 'Spade', 'Diamond', 'Club'];

Ranks = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'];
