// Generated by CoffeeScript 1.9.3
var Dealer,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Dealer = (function(superClass) {
  extend(Dealer, superClass);

  function Dealer(name, hand, deck) {
    this.deck = deck;
    Dealer.__super__.constructor.call(this, name, hand);
    return this;
  }

  return Dealer;

})(Player);
