// Generated by CoffeeScript 1.9.3
var Deck;

Deck = (function() {
  function Deck(decks) {
    var j, k, len, len1, rank, suit;
    if (decks == null) {
      decks = 1;
    }
    this.cards = [];
    this.discarded = [];
    while ((decks -= 1) + 1) {
      for (j = 0, len = Suits.length; j < len; j++) {
        suit = Suits[j];
        for (k = 0, len1 = Ranks.length; k < len1; k++) {
          rank = Ranks[k];
          this.cards.push(new Card(suit, rank));
        }
      }
    }
    this.shuffle();
  }

  Deck.prototype.shuffle = function() {
    var i, swapIndex, temp;
    i = this.cards.length;
    while (i -= 1) {
      temp = this.cards[i];
      swapIndex = Math.floor(Math.random() * i);
      this.cards[i] = this.cards[swapIndex];
      this.cards[swapIndex] = temp;
    }
  };

  Deck.prototype.deal = function() {
    return this.cards.pop();
  };

  Deck.prototype.discard = function(card) {
    this.discarded.push(card);
  };

  Deck.prototype.addCards = function(cards) {
    this.cards.push(cards);
  };

  return Deck;

})();
