// Generated by CoffeeScript 1.9.3
var Hand;

Hand = (function() {
  function Hand() {
    this.cards = [];
  }

  Hand.prototype.addCard = function(card) {
    this.cards.push(card);
  };

  Hand.prototype.discardCard = function(removeCard) {
    var ax;
    while ((ax = this.cards.indexOf(removeCard)) !== -1) {
      this.cards.splice(ax, 1);
    }
    return this.cards;
  };

  return Hand;

})();
